# this is only used for running the tests, there are docs though on using
# ecs compose that are worth reading before we refactor it away for good

version: '2'
services:
  api:
    build: .
    container_name: CliqueApi
    image: '122137487413.dkr.ecr.us-west-2.amazonaws.com/xdam-clique-api:latest'
    ports:
      - 16006:16006
      - 43554:43554
    volumes:
      -  .:/app
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - SERVER_HOST=${SERVER_HOST}
      - CACHE_STORE=${CACHE_STORE}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SERVERLESS_S3_BUCKET_NAME=${SERVERLESS_S3_BUCKET_NAME}
      - SERVERLESS_AWS_ACCESS_KEY_ID=${SERVERLESS_AWS_ACCESS_KEY_ID}
      - SERVERLESS_AWS_SECRET_ACCESS_KEY=${SERVERLESS_AWS_SECRET_ACCESS_KEY}
      - SERVERLESS_AWS_REGION=${SERVERLESS_AWS_REGION}
      - KEYMETRICS_PUBLIC=${KEYMETRICS_PUBLIC}
      - KEYMETRICS_SECRET=${KEYMETRICS_SECRET}
      - REDIS_ADDRESS=${REDIS_ADDRESS}

